### PR TITLE
fixes #345: panic when resp == nil

### LINKED ISSUE #345: panics when cannot receive response
To reproduce:
1. Run the simple proxy example.
2. Use `wget` to send it a request to a website that is down.

Don't see a reason to panic, why just don't call the DoHandler if the proxy failed to get a response?

### PR DESCRIPTION
**Pull request by kubistika**
#345

### CODE REVIEW

**Comment by elazar-lb** [comment]
Thanks,
Wouldn't it be better to handle `nil` yourself in the handler?

**Comment by azak-azkaran** [comment]
> Thanks,
> Wouldn't it be better to handle `nil` yourself in the handler?

I think so too, but I think there is another bug corresponding to this one:

If the response is `nil` the following lines will end in a panic in Line [132](https://github.com/elazarl/goproxy/blob/6125c262ffb039dd0fdb9ba51987c0ac57b4a124/proxy.go#L132):
https://github.com/elazarl/goproxy/blob/6125c262ffb039dd0fdb9ba51987c0ac57b4a124/proxy.go#L130-L132

**Comment by kubistika** [comment]
@elazar-lb @azak-azkaran that's the exact problem. Nil can not be handled by client, that why this pr is necessary

**Comment by elazarl** [comment]
I see, is there a PR solving the panic only?

**Comment by azak-azkaran** [comment]
I think if we move the error handling:
https://github.com/elazarl/goproxy/blob/6125c262ffb039dd0fdb9ba51987c0ac57b4a124/proxy.go#L121-L125

The solution becomes cleaner, what do you think? 
I added my proposed solution and a test case in the provided file: [345.txt](https://github.com/elazarl/goproxy/files/3358889/345.txt)

**Comment by kubistika** [comment]
@azak-azkaran looks better, i'll update
And yes, it solves the panic

**Pull request closed without merging**
