### PR TITLE
send Connection: close header to client only when needed

### PR DESCRIPTION
**Pull request by jakecoffman**
This fixes the inability to reuse connections by only setting the Connection: close header when the client or remote server requests it.

This also pulls in changes by @hmarr in #333 to explicitly terminate the connection instead of relying on an EOF from the client.

### CODE REVIEW

**Comment by jeffwidman** [comment]
@elazarl Sorry to bother, but I noticed this one's been floating for several months... I know the :dependabot: team currently uses a fork of Goproxy incorporating the change in #333 (which this PR includes) internally so it's already seen some prod traffic with no issues.

Any chance you could take a look? I'm sure they'd like to switch back to using upstream instead of a fork.

**Comment by jakecoffman** [comment]
We actually found this change might be problematic and we're testing without it to compare. So hold off on merging for now. Thanks @jeffwidman!

**Comment by jeffwidman** [comment]
Oh interesting. Since this PR includes two changes, are you observing the problem with #333 or with the other change in this PR?

**Comment by elazarl** [comment]
Let me know, and I'll merge whatever you deem helpful.

Thanks!

**Comment by jakecoffman** [comment]
The problem is the change in #333. We observed `write: connection reset by peer` when doing Bundler updates which went away when we removed those lines in #333. 

Now that we're running without that change we're seeing less timeouts. 

I think there are some changes in this PR that we might still want, like not setting the Close header after each request, but I'd like to run it in Dependabot production for a bit to ensure it's good first.

You can close #333!

**Pull request closed without merging**
