### PR TITLE
Switch to better maintained go-charset fork (Closes: #134).

### PR DESCRIPTION
**Pull request by onlyjob**
When this is merged it would be great to tag new formal release. Thanks.

### CODE REVIEW

**Comment by elazarl** [comment]
That would be great idea.

But I've already did that once, from the google code to rog pepe.

How can we find a repository that would be maintained in the long run?

**Comment by onlyjob** [comment]
Well, google code is gone and at the moment I suggest we switch to project that is currently best maintained. I doubt you can find guarantees that it will stay like this forever. One simply have to adapt to changes. Let's hope that new _go-charset_ proves itself to be the best. :)

**Comment by onlyjob** [comment]
Also worth noticing that nobody can use rogpepe/go-charset due to licensing problems so there is a bigger problem than poorly maintained dependency...

**Comment by ErikPelli** [comment]
I completely removed this dependency in https://github.com/elazarl/goproxy/pull/580. Closing this PR.

**Pull request closed without merging**
