### PR TITLE
Add go.mod to make project Go modules compatible

### PR DESCRIPTION
**Pull request by hmarr**
That.

### CODE REVIEW

**Comment by elazar-lb** [comment]
Thanks! 
I really really wanted this kind of PR!

One question.
Can we push these dependencies to the examples dir? So that goproxy itself would remain dependency less?

**Comment by hmarr** [comment]
Good point - I hadn't realised those dependencies were specific to the examples. Done!

**Comment by elazarl** [comment]
@hmarr sorry to nag, but shouldn't the `go.sum` at root be empty as well?

**Comment by hmarr** [comment]
Good point - fixed.

Running `go mod tidy` brought back the `github.com/rogpeppe/go-charset` dependency in the top-level `go.mod`, as the `ext/html` package depends on it, so I had to create an additional `go.mod` in `ext`.

**Pull request merged**
