### PR TITLE
close response body after reading it

### PR DESCRIPTION
**Pull request by ArielBadichi**

### CODE REVIEW

**Comment by elazarl** [comment]
Hi,

Can you add a test case which is solved by the commit? Would help me understand it.

**Comment by ArielBadichi** [comment]
Added test case.

**Comment by elazarl** [comment]
Thanks, would have a look later today.

**Comment by elazarl** [comment]
Would take care of that shortly, have had busy days.

Sorry.

**Comment by ErikPelli** [comment]
In the current master branch, body is closed with a defer. Closing this PR.

**Pull request closed without merging**
