### PR TITLE
Adding new "HTTPMitmNewConnect" method and "Proxy-Authorization" header on NewConnectDialToProxy method

### PR DESCRIPTION
**Pull request by rahulwa**
- Added "HTTPMitmNewConnect" ConnectAction to do HTTP CONNECT request after running all OnRequest methods.
- Added a "Proxy-Authorization" header while using NewConnectDialToProxy if "user:password" are present in url to allow Proxy Authentication.

### CODE REVIEW

**Comment by rahulwa** [comment]
@elazarl I am using this goproxy as main proxy (like haproxy) and forwarding request to next level of proxies (squid servers). And i am doing some sort of roundrobin as OnRequest handler before forwarding. So 
- [1](https://github.com/elazarl/goproxy/pull/210/commits/411cd9394f7378acf9b056f07c38686f277b4add) commit helps to do roundrobin. It allows OnRequest handlers to run before connecting to next proxies servers.
- [2](https://github.com/elazarl/goproxy/pull/210/commits/64edb8376fc6d8f37b07e6f4ec3faff3a593b231) commit allows to handle authentication of next level of proxies.

**Comment by elazarl** [comment]
Hi,
It seems that you need a reverse proxy.
Isn't that the case?
goproxy is supposed to be a regular proxy.

**Comment by rahulwa** [comment]
Hello @elazarl ,
For clients, my proxy is appears to be just a normal forward proxy and internally it does forward request to next level of forward proxies servers. (client => my proxy => proxies servers => google.com (Internet)).
I didn't wanted to make any modification for existing goproxy behaviour. so i made different `HTTPMitmNewConnect` method. I can make any relevant changes to my code, if needed. 
I believe its healthy addition of use case. 
If you don't like it, feel free me to tell me.

**Comment by elazarl** [comment]
I understand the use case, but there are many other reverse proxies, and I
was always sure they're doing a much better job for this use case.

**Comment by rahulwa** [comment]
Yes, you are correct. But i needed something like `OnResponse` and `OnRequest` functions and goproxy provided this. goproxy is very customizable, and it very easy to extend.

**Comment by rahulwa** [comment]
closing it for now.

**Comment by rahulwa** [comment]
If anybody interested, checkout:
https://github.com/rahulwa/camouflage/tree/builtinReverseProxy
https://github.com/rahulwa/camouflage

**Pull request closed without merging**
