### PR TITLE
Rewrite readme

### PR DESCRIPTION
**Pull request by ErikPelli**
Rewrite project readme to include new updates and make it more appropriate.
This PR also updates x/net dependency.

### CODE REVIEW

**Comment by ErikPelli** [comment]
@elazarl what do you think about this new readme? Can it be merged?
Here there is a link with the formatted preview so you can check it better: https://github.com/elazarl/goproxy/blob/5e122f936680ff0d35271525e2791b3ce47b095d/README.md

**Comment by elazarl** [comment]
@ErikPelli truly amazing.  IMHO _italics_ emphasizes better than `code`.

Let's merge!

**Comment by ErikPelli** [comment]
Do you prefer italic style? I could change it if you want

**Comment by elazarl** [comment]
> Do you prefer italic style? I could change it if you want

Let me explain

> The proxy itself is simply a net/http handler,

Here it's great to have `net/http` as code, as this is a piece of code.

> The target of this project is to offer an optimized proxy server,

Here _optimized_ is more appropriate, as it is an English word, and not a piece of code that could appear in the source.

Does that make sense?

**Comment by elazarl** [comment]
NM, that's a cool style, and let's keep it as it is for the time being. I like it when your fingerprints are felt over the project.

I'll take the oppurtunity to thank you for the tremndous work and effort you invest in the project. It is felt and is hearwarming.

**Pull request merged**
