### PR TITLE
 Do not modify headers in response to a HEAD request

### PR DESCRIPTION
**Pull request by sburton84**
Currently GoProxy always removes the `Content-Length` header from any response, and replaces the body with chunked encoding. This does not really make sense to apply to `HEAD` requests, which will have no body in the response, and may rely on the `Content-Length` being returned.

Use-case: The Docker Registry API sends a `HEAD` request to determine if a blob for a particular layer already exists in the repository. It expects that, if the blob exists, the response will be a `200 OK` and will contain a `Content-Length` header indicating the size of the blob. If GoProxy strips the header, then Docker thinks that the blob does not exist, and always tries to reupload every blob. This change allows GoProxy to correctly proxy the Docker Registry API.

### CODE REVIEW

**Comment by sburton84** [comment]
Looking further into this, I'm not sure I understand the need to convert to chunked encoding at all? What was the reasoning behind this? I don't see why we can't just write the response back to the client unchanged like so:

```
if err := resp.Write(rawClientTls); err != nil {
  ctx.Warnf("Cannot write TLS response from mitm'd client: %v", err)
  return
}		
```

I don't think it matters that we don't know the size of the body, it is an `io.Reader` so needn't be all read into memory in one go, and Go will parse it correctly whether it has `Content-Length` or is chunked and will return `EOF` appropriately when the end is reached.

**Comment by elazarl** [comment]
@sburton84 the problem is you don't know in advance how much will be written

**Comment by sburton84** [comment]
> @sburton84 the problem is you don't know in advance how much will be written

But why does it matter? The handler is running inside a goroutine and the reader and writer are streams so there's no reason you can't just stream from the reader to the writer until you reach EOF.

**Comment by elazarl** [comment]
The only way to stream, is not to set the `Content-Length` header.

**Comment by sburton84** [comment]
That's not true, streaming the data this way makes no difference to the client as it's just a stream of bytes, no different to how it would receive any HTTP body from the network whether it has a `Content-Length` header or not. The only difference the header makes is that without one you need to indicate the end of the body by closing the socket.

Either way, as long as you assume the upstream server is behaving correctly, there's no reason you can't forward whatever headers it provides then stream the body that it provides. Doing this the client will receive the exact same data that any direct client to the upstream server would have received.

**Comment by RoganDawes** [comment]
HTTP is a bit annoying in its handling of the HEAD method.
Essentially you need to keep track of whether the request method was GET or HEAD. 
If the method is a GET, and the response has a Content-Length header, you should wrap the response content stream with an io.LimitedReader set to the value in the Content-Length header. 
However, if the request method was HEAD, and the response has a Content-Length header, you should wrap the response content stream with an io.LimitedReader set to 0. Or some other way to indicate that there is no actual content to be sent.

**Comment by ErikPelli** [comment]
Fixed by https://github.com/elazarl/goproxy/pull/473

**Pull request closed without merging**
