### PR TITLE
Add tls.Certificate to proxy struct

### PR DESCRIPTION
**Pull request by astoliarov**
This pull request add tls.Certificate field to proxy struct. This prevent goproxy users from changing global ConnectAction's and GoproxyCA when they need to set custom certificate.
Also add helper: ParseCa create tls.Certificate from cert and key files

### CODE REVIEW

**Comment by elazarl** [comment]
Can't you use the https function for that?

**Comment by astoliarov** [comment]
Maybe. Could you give an example of code which do the thing?

**Comment by astoliarov** [comment]
For me it was hard to understand where I need to put my own certificate when I start looking at goproxy and I found best explanation in customca example. This patch make it easier.
Also, after this patch we can run multiple proxies with different ca inside one app

**Comment by astoliarov** [comment]
@elazarl sorry for pinging, but maybe you can review my PR again?

Thanks

**Comment by astoliarov** [comment]
Found how to do the thing.

**Pull request closed without merging**
