### PR TITLE
Rename examples

### PR DESCRIPTION
**Pull request by pmezard**
Hello,

Here is a bit of work on the examples and their documentation. The first changeset is a big rename, I prefer to discuss it before moving forward. Tell me if you want it done differently. More will follow once this pull-request is merged.

### CODE REVIEW

**Comment by elazarl** [comment]
Hi,

Thanks for the PR.

The naming change looks like a stutter to me.

Why do you need to repeat goproxy in the examples name, it already at `github.com/elazarl/goproxy/example/foo`. Why do you need to have another `goproxy-` prefix?

**Comment by pmezard** [comment]
I suggested it here https://groups.google.com/d/msg/goproxy-dev/1-JW__ZhhFA/7fs2HEoOBzcJ , it is to avoid polluting Go bin directory with random binaries from examples. I can remove it if you are not convinced, that is why I wanted to start with the renaming business.

**Comment by elazarl** [comment]
Hmmm... maybe we should put those directories inside "internal" folder, so that they won't be built?

Can you ask golang-nuts what's the best practice with including examples in your repo, without polluting bin/ namespace? This is a good point (I personally rarely use `...`, but obviously some people do...).

**Comment by pmezard** [comment]
Followup here https://groups.google.com/forum/#!topic/golang-nuts/6JeU_A01vzg . Matthew idea of using build tags sounds smarter than my prefixing.

**Pull request merged**
