### PR TITLE
Improve certstorage example

### PR DESCRIPTION
**Pull request by tetafro**
I've added more info and one more example to `CertStore` example.

I actually just looked through these discussions and copied useful information, so all credits to people from there:

- https://github.com/elazarl/goproxy/pull/332
- https://github.com/elazarl/goproxy/pull/330
- https://github.com/elazarl/goproxy/pull/284

### CODE REVIEW

**Comment by ErikPelli** [comment]
Having a mutx for every single host looks like an anti-pattern to me.
This will also cause memory leaks if there are a lot of different hosts, since the older one are never cleaned uo.

**Comment by tetafro** [comment]
I don't really remember my thinking from 4 years ago, but looks like it's just the most straight-forward example I could come up with.
This definitely can be improved in real life, using some caching with eviction policy instead of a map.

**Comment by ErikPelli** [comment]
Uhm ok, do you think it should still be merged or the current simple example is enough as a simple example for someone that never used this library? (Do you still use it?)

**Comment by tetafro** [comment]
Wait, I just noticed that you did pretty much the same in the [current example](https://github.com/elazarl/goproxy/blob/master/examples/certstorage/cache.go). Why are we discussing this PR then? Let's just close it.

**Pull request closed without merging**
